project/core/views.py
from flask import render_template,request,Blueprint

core=Blueprint('core',__name__)

@core.route('/')
@core.route('/home')
def index():
    return render_template('index.html')

@core.route('/info')
def info():   
    # general info about company
    return render_template('info.html')

@core.route('/contactus')
def contactus():
    return render_template('contactus.html')

project/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from project import db
from project.models import User, Data
from project.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from project.users.picture_handler import add_profile_pic
import stripe
import re
import pandas as pd
import numpy as np
import os
import joblib as jb
import math
import os
from project.users.map import fetch_for_app



model_path = 'project/users/diseasepred.pkl'
model = jb.load(model_path)

from model.req import symptoms
from model.req import disease_dict
from model.req import description_dict
from model.req import medications_description

for i in range(len(symptoms)):
    if '_' in symptoms[i]:
        symptoms[i] = symptoms[i].replace('_', ' ')
        


def getMedicines(dic, prediction):
    df = pd.read_csv('model/medications.csv')
    for key, value in dic.items():
        if value == prediction[0]:
            for i in range(len(df)):
                row = df.iloc[i, :2]
                if row[0] == key:
                    return row[1]
    return "No medicine found"


def suggestedDiets(dic, prediction):
    df = pd.read_csv('model/diets.csv')
    for key, value in dic.items():
        if value == prediction[0]:
            for i in range(len(df)):
                row = df.iloc[i, :2]
                if row[0] == key:
                    return row[1]
                
# def get_user_location():
#     # Return hardcoded location for testing
#     return 23.5470, 87.2902

# def find_nearby_hospitals(latitude, longitude, radius=2000):
#     # Use Overpass API to find nearby hospitals
#     overpass_url = "http://overpass-api.de/api/interpreter"
#     query = f"""
#     [out:json];
#     node["amenity"="hospital"](around:{radius},{latitude},{longitude});
#     out body;
#     """
#     response = requests.get(overpass_url, params={'data': query})
#     data = response.json()
#     return data['elements']

# def calculate_bearing(lat1, lon1, lat2, lon2):
#     lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
#     dlon = lon2 - lon1
#     x = math.sin(dlon) * math.cos(lat2)
#     y = math.cos(lat1) * math.sin(lat2) - math.sin(lat1) * math.cos(lat2) * math.cos(dlon)
#     initial_bearing = math.atan2(x, y)
#     compass_bearing = (math.degrees(initial_bearing) + 360) % 360
#     return compass_bearing

# def create_map(latitude, longitude, hospitals):
#     user_map = folium.Map(
#         location=[latitude, longitude],
#         zoom_start=13,
#         tiles='CartoDB positron',  # More realistic tile style
#         attr='&copy; <a href="http://stamen.com">Stamen Design</a> | Data by <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
#     )

#     folium.Marker(
#         [latitude, longitude], 
#         tooltip="You are here", 
#         icon=folium.Icon(color="blue", icon='info-sign')
#     ).add_to(user_map)

#     marker_cluster = MarkerCluster().add_to(user_map)

#     for hospital in hospitals:
#         hosp_lat = hospital['lat']
#         hosp_lon = hospital['lon']
#         hosp_name = hospital.get('tags', {}).get('name', 'Unnamed Hospital')
#         hosp_address = hospital.get('tags', {}).get('addr:full', 'Address not available')
#         hosp_phone = hospital.get('tags', {}).get('phone', 'No phone number available')  # Extract phone number

#         user_location = (latitude, longitude)
#         hospital_location = (hosp_lat, hosp_lon)

#         distance = geodesic(user_location, hospital_location).kilometers
#         bearing = calculate_bearing(latitude, longitude, hosp_lat, hosp_lon)

#         direction = ""
#         if bearing >= 0 and bearing < 90:
#             direction = "NE"
#         elif bearing >= 90 and bearing < 180:
#             direction = "SE"
#         elif bearing >= 180 and bearing < 270:
#             direction = "SW"
#         else:
#             direction = "NW"

#         popup_text = f"""
#         <div style="font-size: 16px; line-height: 1.5; color: #333; background-color: #fff; border-radius: 8px; padding: 10px; border: 1px solid #ddd;">
#             <strong style="font-size: 18px;">{hosp_name}</strong><br>
#             <em>Address: {hosp_address}</em><br>
#             Phone: <strong>{hosp_phone}</strong><br>
#             Distance: <strong style="color: green;">{distance:.2f} km</strong><br>
#             Direction: {direction}<br>
#             <a href='https://www.openstreetmap.org/directions?mlat={hosp_lat}&mlon={hosp_lon}#map=17/{hosp_lat}/{hosp_lon}' target='_blank' style="color: blue; text-decoration: underline;">Get Directions</a>
#         </div>
#         """
#         folium.Marker(
#             [hosp_lat, hosp_lon],
#             popup=folium.Popup(popup_text, max_width=300),
#             icon=folium.Icon(color="red", icon='hospital-o')
#         ).add_to(marker_cluster)

#     # Legend for the map
#     legend_html = """
#     <div style="position: fixed; 
#                 bottom: 10px; left: 10px; width: 240px; height: auto; 
#                 background-color: rgba(255, 255, 255, 0.8); z-index:9999; border:2px solid grey; 
#                 font-size:14px; padding: 10px; border-radius: 5px;">
#     <i class="fa fa-map-marker" style="color:blue"></i>&nbsp;You are here<br>
#     <i class="fa fa-map-marker" style="color:red"></i>&nbsp;Nearby Hospitals<br>
#     <p>Click on the markers for details!</p>
#     </div>
#     """
#     user_map.get_root().html.add_child(folium.Element(legend_html))

#     return user_map

# def save_map(map_object, file_path):
#     os.makedirs(os.path.dirname(file_path), exist_ok=True)
#     map_object.save(file_path)
# # Main execution
# latitude, longitude = get_user_location()
# nearby_hospitals = find_nearby_hospitals(latitude, longitude)
# hospital_map = create_map(latitude, longitude, nearby_hospitals)
# save_map(hospital_map, os.path.join("project", "static", "hospitals.html"))




# Load Stripe keys from environment variables
public_key = os.getenv('STRIPE_PUBLIC_KEY')
stripe.api_key = os.getenv('STRIPE_SECRET_KEY')

users = Blueprint('users', __name__)

# Register
@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.data'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        login_user(user)
        flash(f"Account created successfully! You are now logged in as {user.username}", category='success')
        return redirect(url_for('users.data'))

    return render_template('register.html', form=form)

# Login
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Log in Success!', category='success')

            next = request.args.get('next')
            if not next or not next.startswith('/'):
                next = url_for("users.data")

            return redirect(next)
        else:
            flash('Invalid email or password', category='danger')

    return render_template('login.html', form=form)

# Logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# Account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!', category='success')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)




        
@users.route('/data', methods=['GET'])
def data():
    # Corrected path
    path = os.path.join("project", "static", "hospitals.html")
    fetch_for_app()  # Call the function to generate the map
    return render_template('data.html')

@users.route('/predict', methods=['POST'])
def predict():
    disease_name = None
    description = None
    medicine = None
    diet = None
    descriptions = None

    # Get symptoms input from form
    paragraph = request.form.get('paragraph')
    print("Received symptoms:", paragraph)
    
    if paragraph:
        # Find symptoms mentioned in the input paragraph (ignoring case)
        found_symptoms = [symptom for symptom in symptoms if re.search(r'\b{}\b'.format(re.escape(symptom)), paragraph.lower())]

        # Create the symptom vector (1 if found, 0 if not)
        symptom_vector = [1 if symptom in found_symptoms else 0 for symptom in symptoms]
        symptom_vector = np.array(symptom_vector).reshape(1, -1)
        
        # Make prediction based on symptom vector
        prediction = model.predict(symptom_vector)
        predicted_disease_value = prediction[0]  # Get the predicted disease value
        
        # Get disease name from disease dictionary
        disease_name = [key for key, value in disease_dict.items() if value == predicted_disease_value]
        
        if disease_name:
            key = disease_name[0]  # The disease name (first found match)

project/templates/account.html
{% extends 'base.html' %}
{% block content %}
    <style>
        body {
            background-image: url("https://images.pexels.com/photos/7150986/pexels-photo-7150986.jpeg?auto=compress&cs=tinysrgb&w=800");
            background-size: cover;
            background-repeat: no-repeat;
        }
        .form-group label {
            font-weight: bold;
            color: black;
            font-size:1.3rem;
        }
        .form-groups{
            scale:1.5;
        }
    </style>
    <div style="margin: 10%;">
        <div class="jumbotron" style="background-color: rgba(245, 245, 245, 0.1);">
            <div class="text-center">
                <h1>Welcome to the page for {{current_user.username}}</h1>
                <img src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}" class="img-fluid rounded-circle mt-3" style="max-width: 200px;" alt="Profile Picture">
            </div>
        </div>
        <div class="container">
            <form method="POST" action="" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                <div class="form-group">
                    {{form.username.label(class='form-group')}}
                    {{form.username(class='form-control')}}
                </div>
                
                <div class="form-group">
                    {{form.email.label(class='form-group')}}
                    {{form.email(class='form-control')}}
                </div>
                
                <div class="form-group">
                    {{form.picture.label(class='form-group')}}
                    {{form.picture(class='form-control')}}
                </div>
                
                <div class="form-groups text-center">
                    {{form.submit(class='btn btn-primary')}}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: rgb(143, 138, 131);
            background: url('https://images.pexels.com/photos/3683113/pexels-photo-3683113.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2') no-repeat fixed center; 
            background-size: cover;
        }
        
        .navbar {
            background-color: rgba(255, 255, 255, 0.9);
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        
        .nav-link {
            color: #333;
            font-size: 1.25rem;
            font-weight: 700;
            cursor: pointer;
            text-decoration: none;
            transition: color 0.3s ease, transform 0.3s ease;
        }
        
        .nav-link:hover {
            color: #28a745; /* Bootstrap success color */
            transform: scale(1.1);
        }
        
        .navbar-brand {
            display: flex;
            align-items: center;
            font-size: 1.5rem;
            color: #333;
            font-weight: 700;
        }

        .navbar-brand img {
            margin-right: 10px;
            height: 50px;
        }
        
        .container {
            padding: 2rem 1rem;
        }

        .footer {
            position: fixed; 
            left: 0; 
            bottom: 0; 
            width: 100%; 
            background-color: #343a40; 
            padding: 1rem 0; 
            color: #f8f9fa;
        }
        
        .footer p {
            margin-bottom: 0;
            font-size: 1rem;
        }

        @media(max-width: 768px){
            .nav-link {
                font-size: 1rem;
            }
            .navbar-brand {
                font-size: 1.2rem;
            }
        }
        
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('core.index') }}">
                <img src="{{ url_for('static', filename='CCA.jpeg') }}" alt="Logo">
                CCA
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('core.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.info') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.contactus') }}">Contact us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.data') }}">Predictor</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" id="home">
        {% block content %}
        {% endblock content %}
    </div>

    <footer class="footer text-center">
        <p>&copy; Design by RnD, CCA</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const navLinks = document.querySelectorAll('.navbar-nav a[href^="#"]');
            
            navLinks.forEach(function(link) {
              link.addEventListener("click", function(e) {
                e.preventDefault();
                
                const targetId = this.getAttribute("href");
                const targetElement = document.querySelector(targetId);
                
                if (targetElement) {
                  const offsetTop = targetElement.offsetTop;
                  window.scrollTo({
                    top: offsetTop,
                    behavior: "smooth"
                  });
                }
              });
            });
        });
    </script>
</body>
</html>

project/templates/contactus.html
{% extends 'base.html' %}

{% block content %}

<div class="container mb-5 d-flex justify-content-center" style="display:flex;flex-direction:column;justify-content:center;padding:130px;">
  <div class="card" style="background-color: rgba(250, 250, 250, 0.5); font-size: 1.5rem; width: 100%; max-width: 900px;">
      <div class="card-header text-center">
          <h2><b>Get In Touch</b></h2>
      </div>
      <div class="card-body">
          <form>
              <div class="form-group">
                  <label for="firstName" style="font-weight: bold;">First Name</label>
                  <input type="text" class="form-control" id="firstName" placeholder="First name">
              </div>
              <div class="form-group">
                  <label for="lastName" style="font-weight: bold;">Last Name</label>
                  <input type="text" class="form-control" id="lastName" placeholder="Last name">
              </div>
              <div class="form-group">
                  <label for="inputEmail4" style="font-weight: bold;">Email</label>
                  <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
              </div>
              <div class="form-group">
                  <label for="inputAddress" style="font-weight: bold;">Address</label>
                  <textarea class="form-control" rows="5" id="inputAddress" placeholder="Address"></textarea>
              </div>
              <button type="submit" class="btn btn-success btn-block">Submit</button>
          </form>
      </div>
  </div>
</div>


  {% endblock %}

project/templates/data.html
{% extends 'base.html' %}

{% block content %}
<style>

    .btn{
        text-align: center;
        justify-content: center; 
        color: black; 
        font-size: 1.5rem;
    }
    .btn:hover{
        background-color: #0056b3;
        color:black;
        transition:color 0.2s ease;
        font-size:1.1rem;
        transition:font-size 0.15s ease;
    }
    #icon{
    padding: 5px;
    }
</style>
<div class="container">
    <h1 class="title">Disease Predictor</h1>
    <div class="row">
        <div class="col">
            <button class="btn" id="start-button">
                <i class="fas fa-microphone" id="icon"></i>Start Voice Input</button>
            <textarea id="symptoms-input" class="textarea" rows="4" placeholder="Symptoms will appear here..."></textarea>
            <button class="btn" id="predict-button">
                <i class="fas fa-bullseye" id="icon"></i>Predict</button>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div id="result" class="output"></div>
        </div>
    </div>
</div>

<script>
    const startButton = document.getElementById('start-button');
    const symptomsInput = document.getElementById('symptoms-input');
    const predictButton = document.getElementById('predict-button');
    const resultDiv = document.getElementById('result');

    // Function to start speech recognition
    function startVoiceInput() {
        if ('webkitSpeechRecognition' in window) {
            const recognition = new webkitSpeechRecognition();
            recognition.continuous = false;
            recognition.interimResults = false;
            recognition.lang = 'en-US';

            recognition.onstart = () => {
                startButton.disabled = true;
            };

            recognition.onresult = (event) => {
                const transcript = event.results[0][0].transcript;
                const symptoms = transcript;
                symptomsInput.value = symptoms;
            };

            recognition.onerror = (event) => {
                console.error(event.error);
                startButton.disabled = false;
            };

            recognition.onend = () => {
                startButton.disabled = false;
            };

            recognition.start();
        } else {
            alert('Speech recognition not supported in this browser.');
        }
    }

    // Function to predict the disease
    function predictDisease() {
        const paragraph = symptomsInput.value;

        fetch('/predict', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: new URLSearchParams({
                'paragraph': paragraph
            })
        })
        .then(response => response.text())
        .then(data => {
            resultDiv.innerHTML = data;

            const medicineButton = document.getElementById('medicine-button');
            const dietButton = document.getElementById('diet-button');
            const medicineDiv = document.getElementById('medicine');
            const dietDiv = document.getElementById('diet');

            medicineButton.addEventListener('click', () => {
                medicineDiv.style.display = 'block';
                dietDiv.style.display = 'none';
            });

            dietButton.addEventListener('click', () => {
                dietDiv.style.display = 'block';
                medicineDiv.style.display = 'none';
            });
        })
        .catch(error => console.error('Error:', error));
    }

    startButton.addEventListener('click', startVoiceInput);
    predictButton.addEventListener('click', predictDisease);
</script>

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 100%;
        margin: 0 auto;
        padding-top: 50px;
        box-sizing: border-box;
    }
    .title {
        text-align: center;
        margin-bottom: 20px;
    }
    .row {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        margin-bottom: 20px;
        width: 100%;
    }
    .col {
        flex: 1;
        max-width: 600px;
        margin: 10px;
    }
    .btn {
        display: block;
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-align: center;
        font-size: 16px;
    }
    .btn:hover {
        background-color: #0056b3;
    }
    .textarea {
        width: 100%;
        padding: 10px;
        font-size: 16px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }
    .output {
        padding: 5px;
        width: 100%;
        max-width: 800px;

    }
</style>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/fontawesome.min.css">
    <style>
        body {
            background-color: #f4f4f4;
            font-family: 'Arial', sans-serif;
        }
        #heading {
            color: rgb(34, 34, 34);
            padding-top: 150px; 
            padding-bottom: 150px; 
            min-height: 90%;
        }
        .brand {
            background-color: rgba(0, 0, 0, 0.1);
            height: 200px;
            margin: 0;
            border-radius: 50px;
            padding: 20px;
            transition: background-color 0.3s ease;
        }
        .brand:hover {
            background-color: rgba(0, 0, 0, 0.2);
        }
        .text {
            background-color: rgba(0, 0, 0, 0.1);
            border-radius: 30px;
            text-align: center;
            justify-content: center;
            font-weight: bold;
            font-family: 'Garamond', serif;
            padding: 70px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        }
        .text h1 {
            font-size: 2.5rem;
            margin: 0;
            color: #2c3e50;
        }
        .btn {
            color: #fff; 
            background-color: #3498db; 
            font-size: 1.5rem;
            padding: 10px 30px;
            border: none;
            border-radius: 50px;
            transition: background-color 0.3s ease, transform 0.2s ease;
        }
        .btn:hover {
            background-color: #2980b9;
            transform: scale(1.05);
        }
        @media (max-width: 1100px) {
            .text {
                font-weight: normal;
                font-size: 2.5rem;
                padding: 50px;
            }
            .brand {
                height: 150px;
            }
            .btn {
                font-size: 1.3rem;
                padding: 8px 20px;
            }
        }
    </style>
    <div class="d-flex flex-column align-items-center justify-content-center text-center" id="heading">
        <img class="brand mb-4" src="{{ url_for('static', filename='logo.png') }}" alt="logo">
        <div class="text p-3">
            <h1 class="display-3">
                Personal Medicine <br>and<br>Diet Recommendation System
            </h1>
            <a class="btn mt-4" href="{{ url_for('users.data') }}">Get Started</a>
        </div>
    </div>
{% endblock content %}

project/templates/info.html
{% extends 'base.html' %}
{% block content %}
    <div class="container d-flex flex-column align-items-center justify-content-center" style="padding: 130px;">
        <div class="card text-center shadow" style="background-color: rgba(245, 245, 245, 0.9); max-width: 800px; border-radius: 20px;">
            <div class="card-header" style="background-color: rgba(0, 0, 0, 0.1); border-bottom: 2px solid rgba(0, 0, 0, 0.2);">
                <p style="font-size: 3rem; font-weight: bold; margin: 0;">RnD, CCA</p>
            </div>
            <div class="card-body">
                <h5 class="card-title" style="font-size: 2rem; font-weight: bold;">About Our Cell</h5>
                <p class="card-text" style="font-size: 1.2rem; text-align: justify; line-height: 1.6;">
                    Since the dawn of the dark ages, groundbreaking discoveries have been made by mankind. Research is a vital aspect of every field. The Research and Development (R&D) Cell thrives on the synergy between young minds and experienced faculty. Established to promote and oversee the research programs of the institute, the cell administers and coordinates these programs. Our goal is to foster a research culture within the college by encouraging innovative research in emerging and challenging areas of Engineering, Technology, Science, and Humanities. Faculty and students are motivated to be creative, as creativity sparks new ideas. We conduct lectures and demonstrations by our faculty and experts, alongside paper presentations and workshops, to ignite the spirit of innovation among students.
                </p>
            </div>
        </div>
    </div>
{% endblock content %}

project/templates/login.html
{% extends 'base.html' %}
{% block content %}

<body>
    <div class="head" style="margin:10%;">
    <div class="text-center">
        <form method="POST" class="form-signin" style="color: rgb(0, 0, 0);font-size: 1.5rem; ">
            {{form.hidden_tag()}}
            <h1 class="h1 mb-3 font-weight-normal" style="padding-top: 20px;">
                Please LogIn!!
            </h1>
            <div class="col-lg-10 mx-auto">
                <div class="text-center">
                    {{form.email.label()}}
                    {{form.email(class="form-control")}}
                    <br>
                    {{form.password.label()}}
                    {{form.password(class="form-control")}}
                    <br>
                </div>
            </div>
            
    
                <div class="col-lg-13 d-flex justify-content-center" id="login">
                    <style>
                        #login{
                        display:flex;
                        flex-direction:row;
                        align-items:centre;
                        justiy-content:center;
                        }
                    </style>
                    {{form.submit(class="btn btn-lg btn-success")}}
                </div>
            <br>
            <div >
                <h6><span class="text-center" style="text-align: center;font-size: 1.5rem;">Do not have an account?</span></h6>
                <a class="btn btn-lg btn-secondary" href="{{ url_for('users.register') }}">Register</a>
             </div>

        </form>
    </div>
</div>
</body>
{% endblock content %}

project/templates/register.html
{% extends 'base.html' %}
{% block content %}
<body class="text-center">
    
    <div class="container" style="margin: 10%;">
        <form method="POST" style="color: rgb(0, 0, 0); font-size: 1.5rem;">
            {{form.hidden_tag()}}
            <h1 class="h1 mb-3 font-weight-normal" style="padding-top: 20px;">
                Please Create Your Account
            </h1>
            <div class="col-lg-8 mx-auto">
                {{form.email.label}}{{form.email(class="form-control")}}
                {{form.username.label}}{{form.username(class="form-control")}}<br>
                {{form.password.label}}{{form.password(class="form-control")}}<br>
                {{form.pass_confirm.label}}{{form.pass_confirm(class="form-control")}}<br>
            </div>
            <div class="col-lg-2 mx-auto d-flex flex-column align-items-center mt-4">
                {{form.submit(class="btn btn-lg btn-block btn-success")}}
                <div class="text-center mt-3">
                    <h6>
                        <span style="font-size: 1.5rem;">Already have an Account?</span>
                    </h6>
                    <a class="btn btn-lg btn-secondary mt-2" href="{{ url_for('users.login') }}">Login</a>
                </div>
            </div>
        </form>
    </div>
</body>

{% endblock content %}